name: Intro to GitHub Actions

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  first-job:
    name: First Job
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 (Код репозитория клонируется в рабочую директорию раннера)
        uses: actions/checkout@v4

      - name: Step 2 (Приветствие)
        run: echo "Hello from GitHub Actions!"

      - name: Step 3 (Поработаем с переменными окружения)
        env:
          MY_VAR: ${{ secrets.PASSWORD }}
        run: |
          echo "MY_VAR is: $MY_VAR"


  second-job:
    name: Second job (runs after show-structure)
    runs-on: ubuntu-latest
    needs: first-job
    steps:
      - name: Step 1 (Инфа, что первый job выполнен успешно)
        run: echo "first-job completed successfully, starting second-job"